### ISSUE TITLE
Tracking codemeta additions

### ISSUE THREAD

**Issue by cboettig** [ropensci-archive/intern#9]
Hi Chris, Grace,

To coordinate on adding `codemeta.json` files to the remaining package, I thought I would migrate the issue over to here.  Below is the set Chris is currently working on.  Grace, it might help if you claim a set as well.  Eventually we want to work through all the packages listed on our website: https://new.ropensci.org/packages/ (that's the beta version, but includes an automatically generated package list from the [roregistry](https://github.com/ropensci/roregistry)).  

Might be easiest to just let you each claim packages from that list here and work through them at your own pace?  

Chris Fan (@chrisfan24)

- [ ] AntWeb - Karthik Ram
- [ ] biomartr - HajkD
- [ ] bittrex - Michael Kane 
- [ ] bold - sckott
- [ ] brranching - sckott
- [ ] camsRad - lukas-rokka
- [ ] ccafs - sckott
- [ ] ckanr - sckott, Imanuel Costigan, Wush Wu, Florian Mayer
- [ ] chromer - Matthew Pennell
- [ ] clifro - blasee

Grace Li, (@graceli8)

- [ ] antiword - Jeroen Ooms 
- [x] assertr - Tony Fischetti
- [x] bikedata - Mark Padgham
- [x] binomen - Scott Chamberlain
- [x] bomrang - Adam Sparks
- [x] crminer - Scott Chamberlain
- [x] crul - Scott Chamberlain
- [ ] eechidna - Ben Marwick
- [x] fulltext - Scott Chamberlain
- [ ] graphql - Jeroen Ooms
- [x] iheatmapr - Alicia Schep
- [ ] magick - Jeroen Ooms
- [x] mapr - Scott Chamberlain
- [x] rebird - Scott Chamberlain
- [x] rfigshare - Carl Boettiger
- [ ] tesseract - Jeroen Ooms
